FROM <image de base>
WORKDIR /app
COPY <source_locale> <destination_conteneur>
RUN <commande_a_executer>
EXPOSE 8000 <a titre informatif>
ENTRYPOINT ["Commande_fixe"]
CMD ["python3", "app.py"] # Commande par defaut (suite de ENTRYPOINT)