version: "3.9"
services:
    <nom_service>:
        image: image_du_conteneur
        build: # si Dockerfile 
            context:  # indiquer le contexte
            dockerfile: Dockerfile
        volumes: # liste de volumes (mappage)
        ports: # liste de ports (mappage)
        networks: liste des reseaux  
volumes:
    <volume-1> : 
    <volume-n> : 
networks:
    <network-1> : 
    <network-n> : 